### ISSUE TITLE
sqratLite.h (from sqmodules.h) clashes with sqrat

### ISSUE THREAD

**Issue by FluXy** [GaijinEntertainment/quirrel#90]
A lot of xxx already declared messages.

The comment at the top in sqmodules.h also states:
/*
  This is not a production code, but a demonstration of concept of modules
*/

is this still the case? :)

**Comment by VasiliyRyabtsev** [comment]
> A lot of xxx already declared messages.

I've updated the code so that it is now switchable between Sqrat and sqratLite, which is only a thing wrapper around Quirrel Object.
It relies on `SQMODULES_HAVE_SQRAT` preprocessor definition though and existence of sqrat.h in path. Please feel free to suggest improvements.

> is this still the case? :)

Well, it should be usable in a limited set of scenarios. For the real world embedded usage it should have a customizable file system abstraction layer. Also such features as `import` syntax and support for static analysis would be useful .
