### ISSUE TITLE
Interactive console(SQ) doesn't include baselib

### ISSUE THREAD

**Issue by DFelipehDEV** [GaijinEntertainment/quirrel#95]
When running baselib functions(print, println, freeze...) in the SQ interpreter, they appear as not included and as variable errors
![image](https://github.com/user-attachments/assets/9dc9f5b7-e224-4224-be5c-4cb75cf58159)

**Comment by VasiliyRyabtsev** [comment]
Thank you for your report!
I will fix this in the next few days.
Unfortunately "interactive" mode in SQ interpreter never was very useful, and it is less useful in the current Quirrel version because of locally scoped variables.
It can be reworked, but needs a serious redesign, and it will be more complex than a trivial sq_compile()/sq_call() pair.

**Comment by DFelipehDEV** [comment]
Hey! Yeah i agree that the console isn't very useful beyond simple tasks like call functions. My goal was to understand how to embed quirrel. Instead of a rework, I would suggest just provide simple samples to demonstrate how it works

**Comment by VasiliyRyabtsev** [comment]
Fixed  in dcef127ab8c3543473bdb058afe27c37a993d014
